apiVersion: "cagip.github.com/v1"
kind: NetworkPolicyConfig
metadata:
  name: kubi-default
spec:
  egress:
    ports:
      - 636
      - 389
      - 123
      - 53
    cidrs:
      - 192.168.2.0/24
      - 172.10.0.0/24
  ingress:
    namespaces:
      - ingress-nginx